### ISSUE TITLE
Running any gradient command produces TypeError

### ISSUE THREAD

**Issue by kevinajordan** [Paperspace/gradient-cli#258]
Running any gradient command in the terminal produces the same error. Whether I run gradient by itself (which should produce a help message) or if I try to set my API key, the same error gets produced. Tracebacks are shown below:

~$ gradient
Traceback (most recent call last):
  File "/home/kevin/.local/bin/gradient", line 5, in <module>
    from gradient import main
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/__init__.py", line 1, in <module>
    from .api_sdk import *
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/__init__.py", line 1, in <module>
    from .clients import *
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/clients/__init__.py", line 1, in <module>
    from .clusters import ClustersClient
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/clients/clusters.py", line 1, in <module>
    from gradient.api_sdk import repositories
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/repositories/__init__.py", line 1, in <module>
    from .clusters import ListClusters
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/repositories/clusters.py", line 7, in <module>
    from gradient.api_sdk.serializers.cluster import ClusterSchema
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/serializers/__init__.py", line 1, in <module>
    from .artifact import ArtifactSchema
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/serializers/artifact.py", line 3, in <module>
    from gradient.api_sdk import models
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/models/__init__.py", line 4, in <module>
    from .deployment import Deployment
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/models/deployment.py", line 5, in <module>
    class Deployment(object):
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/models/deployment.py", line 76, in Deployment
    tags = attr.ib(type=list, factory=list)
TypeError: attrib() got an unexpected keyword argument 'factory'

--------------------------------------------------------------------------------------------------------------
~$ gradient version
Traceback (most recent call last):
  File "/home/kevin/.local/bin/gradient", line 5, in <module>
    from gradient import main
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/__init__.py", line 1, in <module>
    from .api_sdk import *
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/__init__.py", line 1, in <module>
    from .clients import *
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/clients/__init__.py", line 1, in <module>
    from .clusters import ClustersClient
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/clients/clusters.py", line 1, in <module>
    from gradient.api_sdk import repositories
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/repositories/__init__.py", line 1, in <module>
    from .clusters import ListClusters
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/repositories/clusters.py", line 7, in <module>
    from gradient.api_sdk.serializers.cluster import ClusterSchema
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/serializers/__init__.py", line 1, in <module>
    from .artifact import ArtifactSchema
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/serializers/artifact.py", line 3, in <module>
    from gradient.api_sdk import models
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/models/__init__.py", line 4, in <module>
    from .deployment import Deployment
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/models/deployment.py", line 5, in <module>
    class Deployment(object):
  File "/home/kevin/.local/lib/python3.6/site-packages/gradient/api_sdk/models/deployment.py", line 76, in Deployment
    tags = attr.ib(type=list, factory=list)
TypeError: attrib() got an unexpected keyword argument 'factory'

**Comment by kevinajordan** [comment]
Issue was from not running gradient in a virtualenv.
